### ISSUE TITLE
median/examples/multi: median.multi.sig~ only available after adding median.multi

### ISSUE THREAD

**Issue by FrancescElies** [Cycling74/median#3]
Is it expected that `median.multi.sig~` is only available after adding `median.multi`? 

https://user-images.githubusercontent.com/6558089/185285581-7beb0005-103f-49ee-a13e-e98888ae3837.mp4

**Comment by x37v** [comment]
Yeah, I'm aware of this though maybe I can use an init file to indicate that `median.mult.sig~` exists in the `median.multi` binary

**Comment by x37v** [comment]
@FrancescElies sorry for the delayed response..

If you install via `cargo make install` are you still seeing this behavior? There is an [init file](https://github.com/Cycling74/median/blob/develop/median/examples/multi/init/median-multi-objectmappings.txt) that should set up the mapping so that Max knows to look in the `median.multi` binary for `median.multi.sig~`

If `install` doesn't work for you, you could always copy that file into an `init` directory next to `externals`:

```
xnor:~/dev/rust/median/median/examples/multi (develop) find ~/Documents/Max\ 8/Packages/multi/
/Users/xnor/Documents/Max 8/Packages/multi/
/Users/xnor/Documents/Max 8/Packages/multi//init
/Users/xnor/Documents/Max 8/Packages/multi//init/median-multi-objectmappings.txt
/Users/xnor/Documents/Max 8/Packages/multi//externals
/Users/xnor/Documents/Max 8/Packages/multi//externals/median.multi.mxo
/Users/xnor/Documents/Max 8/Packages/multi//externals/median.multi.mxo/Contents
/Users/xnor/Documents/Max 8/Packages/multi//externals/median.multi.mxo/Contents/MacOS
/Users/xnor/Documents/Max 8/Packages/multi//externals/median.multi.mxo/Contents/MacOS/median.multi
/Users/xnor/Documents/Max 8/Packages/multi//externals/median.multi.mxo/Contents/PkgInfo
```

**Comment by FrancescElies** [comment]
@x37v thanks!
